### ISSUE TITLE
SS is not handle renaming containers via agent-cli

### ISSUE THREAD

**Issue by p1gmale0n** [subutai-io/base#1298]
after renaming containers via agent-cli got:
1) on Environment -> Containers - have old names of containers
2) status for containers is UNKNOWN (after click **Check** button)
3) Change name on renamed container return - ERROR!

**Comment by Dilshat** [comment]
If you change container name via CLI , the container record in environment metadata is not updated.
Change is not propagated to initiator peer. This is a current technical limitation.
Since the functionality is intended to be used by environment owner via initiator peer and is not intended to be used by admin of the peer

**Comment by p1gmale0n** [comment]
we can fix this, @Dilshat ?

**Comment by Dilshat** [comment]
No critical, we will evaluate if it is needed at all, since it requires a lot of changes. 
Moreover for Hub envs, it should work well

**Comment by Dilshat** [comment]
wontfix

**Comment by Dilshat** [comment]
Will be solved in the course of this issue https://github.com/subutai-io/base/issues/1626
