### ISSUE TITLE
Need checks to see if configurations are consistent for environments

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#1580]
Management can check that SubOS is consistent, if container’s state has changed that proper routing rules are used if a domain is setup for the environment. Maybe Hub must also do the same. This is extra functionality for making SURE 100% all is ok.

See: 

https://github.com/subutai-io/subos/issues/626

**Comment by Dilshat** [comment]
Seems problematic due to the fact that domain is managed on initiator peer.
Container can reside on remote peer. Container can be stopped manually by admin of remote peer.
In this case we can not find out that container stopped unless we poll remote end which will introduce overhead. Better to implement as close to target as possible, i.e. on subos level
