### ISSUE TITLE
[UI] Incorrect placement of containers over Peers in Env Builder

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/base#1650]
Sometimes in Advanced mode when you click Edit button on a x-peer environment,
the Peers on builder and peers on the right panel are confused.
On the right panel you see, say Peer1 as local peer and Peer2 as remote peer
but on builder you see local containers placed on Peer2 and remote containers placed on Peer1.

**Comment by eabyshev** [comment]
First I delete all indexes in Peers and Resource hosts names, sequence peers on left side and right side were mixed, on each page refresh, value were different. Then I add missed value RH id on ContainerDTO to represent it on FE, after add id instead of indexes. Also fixed showing [MH] on Resouce host.

**Comment by eabyshev** [comment]
done
