### ISSUE TITLE
Find way to notify SS about quota changes

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/base#1685]
We have to notify SS about quota changes
There are several ways but the best i think would be to integrate them to heartbeat

**Comment by soffokl** [comment]
@Dilshat How SS will use information about quota changes? Asking to understand what lagging between actual changes of quota and send notification will be suitable.

**Comment by Dilshat** [comment]
This information will be used for the following purposes:

1. Send info about env & containers to Hub (to be shown to user and used by Orchestration)
2. Display information in UI and let user modify quotas
3. Expose information to **envinfo** binary (to be used from within environment containers)
4. Other usages, not mentioned here

**Comment by Dilshat** [comment]
So basically we can have several minutes lag, I dont think it will be a problem.
We can add additional methods to Quota API to allow obtain a real-time quota if needed

**Comment by akarasulu** [comment]
For both @soffokl and @Dilshat :

> So basically we can have up to a several minutes update interval, I don't think it will be a problem.
We can add additional methods to Quota API to allow obtaining a real-time quota if needed

Hmm this can impact pricing. Minutes however if below 5-10 might be OK but we're pushing it.

> This information will be used for the following purposes:
> 
> 1. Send info about env & containers to Hub (to be shown to user and used by Orchestration)
> 2. Display information in UI and let user modify quotas
> 3. Expose information to **envinfo** binary (to be used from within environment containers)
> 4. Other usages, not mentioned here

Yup pricing is also important. Because quota = container size right ?

This information needs to be synchronized properly. The heartbeat is not the place IMHO. I think the Subutai CLI needs to notify when operations are occurring outside of those driven by the UI. Let's call these **unmanaged** changes verses **managed** changes. How we design that is the question.

SS issues authenticated commands on the agent REST API right? Subutai CLI is executed as a child of the agent and without a TTY right?

If so then the Subutai CLI can definitively know when it is invoked as an agent child processes for SS verses when invoked via a user in a terminal directly. Correct ?

The agent can send unsolicited messages to the management console notifying it of non-SS activity. This should be a mechanism used in general: NOT just for quotas. It should be used for anything that happens via the terminal with Subutai CLI. 

Thoughts?

**Comment by Dilshat** [comment]
Heartbeat is sent only in case something changes. It is already used now and works well, why should we create additional functionality? quotas are related to containers and container info is already present in heartbeat

**Comment by soffokl** [comment]
I agree that it should come in heartbeat. I'll try to add it and we will see.

**Comment by soffokl** [comment]
**unmanaged** changes can be done without CLI, just changing cgroup rules or BTRFS quota.

**Comment by akarasulu** [comment]
I just saw this: before wrote up this https://github.com/subutai-io/agent/issues/60

Wondering how your recommended way with cgroups will work and will it be holistic covering all cases?

**Comment by Dilshat** [comment]
SS side will be handled in the course of issue https://github.com/subutai-io/base/issues/1719
