### ISSUE TITLE
Installation instructions may need more work !

### ISSUE THREAD

**Issue by bmullan** [subutai-io/base#1880]
Trying to install Subutai on an Ubuntu 16.04 x64 machine using instructions found at:

https://subut.ai/installation.html

The instructions are pretty minimal and primarily say:

> After installation you should be ready to share resources. The following components are installed onto your system if not already present:
> Google Chrome Browser
> VirtualBox Hypervisor
> Subutai Social E2E Browser Plugin for Chrome
> Subutai Social Resource host (RH) VM Image for Virtual Box
> Subutai Social Management host (MH) Template Image
> OS Specific Subutai Social P2P Executable
> Subutai Social Tray Application

I added the ppa key, did sudo apt update, then the sudo apt install and everything completed with no errors.

However, If I start Virtual Box I can't see m to find the VM image for Subutai Social Management host (not sure where the above instruction comment intends it was located but its not in VIrtual Box's default for images.

It also did NOT install Chrome as its not on my system.

But I added the plugin to Chromium manually.

Once I launched the "tray" & clicked on its ICON:

if I click on Virtual Machines - nothing happens (not sure what is supposed to though ?)

if I click on "Launch" then click on "Launch SS Console" I see an error message:
"Can't get RH IP address. Error: exit code not null, Exit_Code 1008

If I click on "Launch" then click on "Launch Hub Website" I get "Error Launch Hub Website failed".

On this page (https://github.com/subutai-io/subos/blob/master/Readme.md) the instructions say to install the PPA for snappy-dev/tools **_but snappy-dev/tools has been Deprecated (see the following):_**

https://launchpad.net/~snappy-dev/+archive/ubuntu/tools

I think snappy-tools was replaced by SnapCraft perhaps??

I'm thinking that perhaps the PPA may not be doing everything for installation that it should - and - that the Installation instruction page could use a bit more work and/or some pictures perhaps.

I'm anxious to try Subutai as I'm a long time LXD user and look forward to when I can get some of this up & working.

thanks

Brian

**Comment by tzununbekov** [comment]
@bmullan thank you for your feedback, let me first answer the question about subos repository and deprecated snappy-dev tools.

Subos repository was used to build Subutai snap package using snappy-dev tool and since it was replaced with snapcraft we have moved our snap sources to the new repo - https://github.com/subutai-io/snap    

Snap repository was designed for internal usage of our CI system, so it may looks not so friendly for regular users. Anyway, there are several options to get Subutai snap package: download it from Ubuntu Snap store by [link](https://dashboard.snapcraft.io/dev/snaps/6009/download/rev/30/) (you can install it directly into your system if it supports snap packages: `snap install subutai --devmode`) or build it yourself by running `./configure` script in root of your local [snap](https://github.com/subutai-io/snap) repository and executing `snapcraft` command after it.


About incomplete installation instruction from our website - currently we are about to finish Subutai installer big upgrade which should make all those steps with ppa, apt, sudo, etc. unnecessary at all and as soon as it happen we'll put in order our outdated instruction

**Comment by bmullan** [comment]
Thanks for the update..!
