### ISSUE TITLE
P2P version shows with extra information

### ISSUE THREAD

**Issue by zubaidullo** [subutai-io/base#2106]
P2P version shows extra information like **p2p version 6.1.9-dev**, actually storing just **6.1.9-dev** is enough and right way. So, need to remove **p2p version** part.

**Comment by zubaidullo** [comment]
here is also need to clarify, will p2p send above format always, or it will be changed

**Comment by Dilshat** [comment]
We can have a convention that first line of output will contain the version
And the last word of it will be the version we use

**Comment by crioto** [comment]
Version output done by library we use, so it will not change in time and you can rely on this output. 
All production versions will have the following version format: X.Y.Z
Dev version will always have `-dev` suffix and Z+1, for example if current produdction version is 6.2.3 then p2p dev will be 6.2.4-dev
Same goes to stage, but will have `-master` suffix, instead of `-dev`.

**Comment by zubaidullo** [comment]
before:
![selection_292](https://user-images.githubusercontent.com/4469949/32431843-3c86e696-c2ff-11e7-98cc-3554bf2e1370.png)

after:
![selection_291](https://user-images.githubusercontent.com/4469949/32431847-3f90a412-c2ff-11e7-9b39-abc8cd545412.png)
