### ISSUE TITLE
[Kurjun] [Raw files] Can't recognize when the file is loading.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#807]
If the user clicks on Actions: download file from Raw, he can't recognize that the file is loading, there is no messages or progress bar. 
Looks like: at first file uploads from global to local kurjun and after that the user gets notification about save the file.
![1461912331396](https://cloud.githubusercontent.com/assets/11311924/14910111/7dbca5dc-0e0c-11e6-941b-4ffe6cfe08f1.jpg)

**Comment by kylycht** [comment]
this feature needs to be implemented:
we can provide service that can return % of downloaded artifact between embedded Kurjun and Gorjun.
So maybe have a button ***Cache*** that will fetch this artifact from global Gorjun and after it is available locally ***Download*** button will appear instead of ***Cache***

**Comment by TalasZh** [comment]
fixed with #818
